### PR TITLE
ESXi allows create and configure up to 10 interfaces per VM

### PR DESCRIPTION
**Pull request by hidethecode**

### CODE REVIEW

**Comment by hidethecode** [comment]
these change allows creating and configure more than 4 interfaces per VM

**Comment by josenk** [comment]
Actually, I'm doing my tests right now for a new minor releast that will include this.  :-)  

BTW: There is a couple other places that code needs to be changed and esxi guests support 10 virtual nics, not 11...

**Comment by hidethecode** [comment]
Yes, my fault... of course, 10

**Comment by josenk** [comment]
2.4.3 released with fix.
>https://github.com/josenk/vagrant-vmware-esxi/releases/tag/2.4.3

**Pull request closed without merging**
