### PR TITLE
Add support for public_address capability

### PR DESCRIPTION
**Pull request by ilpianista**
This is useful in combination with the [vagrant address](https://github.com/mkuzmin/vagrant-address) plugin.

### CODE REVIEW

**Comment by josenk** [comment]
I'll fully implement the "vagrant address" command into esxi, so you don't need to install two plugins.

**Comment by ilpianista** [comment]
`vagrant address` isn't a vagrant command by default, but it's provided by the vagrant address plugin.

**Comment by ilpianista** [comment]
With your implementation the output is different because the vagrant-address plugin shows just the IP, while your shows:

    ==> default: 192.168.0.2

So, if you have both plugins installed, the output change depending on the provider.

**Comment by josenk** [comment]
So, I'll assume the other plugin is NOT multi-machine compatible????   What does that plugin do when multiple machines are configured?

I implemented to be multimachine compatible.  Here is an example with two systems...

```
$ vagrant address
==> v-multi1: 192.168.1.249
==> v-multi2: 192.168.1.136
```

**Comment by josenk** [comment]
OK, I don't really like the way that works, but I'll match the output of the other 'address' plugin for a single machine.

I changed my logic.   If there is only 1 host, or you specify a single host on the command line, it will display just the IP.   If there is multiple hosts it will use the vagrant output method...

# Single machine
```
$ vagrant address
192.168.1.249

$ vagrant address default
192.168.1.249
```

# Multi machine
```
$ vagrant address
==> v-multi1: 192.168.1.249
==> v-multi2: 192.168.1.136

$ vagrant address v-multi2
192.168.1.136
```

You can try the pre-release here...   Please test it and let me know if it works as expected.
```
cd /tmp
wget dc002.jintegrate.co/3sdkdf8d43j3j/vagrant-vmware-esxi-2.4.1.gem
vagrant plugin uninstall vagrant-vmware-esxi
vagrant plugin install ./vagrant-vmware-esxi-2.4.1.gem
```

**Comment by ilpianista** [comment]
Ok, I can confirm this work in the same way.

**Pull request closed without merging**
